**Question-1**
Sometimes the data has few duplicate values which will affect the analysis done. In this problem, you will be given a list. You have to find and delete the duplicates and print the updated list with no duplicates.

----------------------------------------------------------------------
Input:
A list of integers.

Output:
A list of integers, with duplicates removed if any.

----------------------------------------------------------------------
Sample input:
[8, 9, 2, 2, 3, 4, 5, 2]

Sample output:
[8, 9, 2, 3, 4, 5]

----------------------------------------------------------------------
Sample input:
[4, 4, 4, 4]

Sample output:
[4]

----------------------------------------------------------------------
Note the order of the data did not change in input and output.


In [2]:
l=eval(input())
ul=[]
for i in l:
    if i not in ul:
        ul.append(i)
print(ul)


1,2,3,33,4,4,5,5,5,5,
[1, 2, 3, 33, 4, 5]


**Question-2**

You will be converting a dictionary, of string(keys) and list of string (values),  to a list of strings. Please check the sample input/output for clarification.


Input:
A dictionary with keys as strings and values as a list of strings.

Output:
A list of strings


Sample input:

{'Mobile': ['Redmi', 'Samsung', 'Realme'], 
'Laptop': ['Dell', 'HP'],
'TV': ['Videocon', 'Sony'] }

Sample output:

['Mobile_Redmi', 'Mobile_Samsung', 'Mobile_Realme', 'Laptop_Dell', 'Laptop_HP', 'TV_Videocon', 'TV_Sony']


Sample input:

{ 'Pen': ['Gel', 'Ink', 'ball'],
'Mobile': ['Android', 'apple'] }

Sample output:

['Pen_Gel', 'Pen_Ink', 'Pen_ball', 'Mobile_Android', 'Mobile_apple']


In [8]:
import ast
d=input()
d=ast.literal_eval(d)
l=[]
for k,*values in d.items():
     for i in d[k]:
        l.append(k+'_'+i)
        
print(l)
        
   


{'Mobile': ['Redmi', 'Samsung', 'Realme'], 'Laptop': ['Dell', 'HP'], 'TV': ['Videocon', 'Sony'] }
['Mobile_Redmi', 'Mobile_Samsung', 'Mobile_Realme', 'Laptop_Dell', 'Laptop_HP', 'TV_Videocon', 'TV_Sony']


**Question-3**

For the purpose of this question, we will define something called an Relevel string. Note that this definition is not valid outside this question. A string Relevel string if the frequency of its characters is something like 1, 2, 3, 4, .... That is a character appears only once, another appears twice, another appears thrice and so on. For example string '$yrr$ssrsr' is a beautiful string since the frequency of y:1, $:2, s:3, r:4, however string '$yrr$ssrsr%' will not be beautiful since it has two characters (y and %) with frequency 1. The frequency of characters should be of form 1, 2, 3, 4, 5... only.
Given a string, can you determine if the string is Relevel string or no?


Input:

A string

Output:

Boolean depending whether the string is Relevel string or not


Sample input:

$yrr$ssrsr

Sample output:

True


Sample input:

$yrr$ssrsr%

Sample output:

False

Sample input:

ab#ab#aba

Sample output:

False

Sample input:

ab#ab#ab6a

Sample output:

True


In [18]:
string=input()
string1=set(string)
dict={}
for i in string1:
    count=0
    for x in string:
            if i==x:
                count=count+1
    dict[i]=count
list1=dict.values()
list1=list(list1)
list1.sort()
count=0
for i in list1:
    count=count+1
    if i!=count:
        print(False)
        break
    elif i==max(list1):
        print(True)

abbcccdddd
True


**Question-4**

You will be given a string with a lot of brackets. You have to print if the brackets are balanced or not. Remember, there are three types of brackets: ‘( )’,  ‘{ }’ and ‘[ ]’.

----------------------------------------------------------------------
Input:

A string

Output:

Yes, if the brackets are balanced.
No otherwise.

----------------------------------------------------------------------
Sample input:

){[[]]}())()

Sample output:

No

----------------------------------------------------------------------
Sample input 2:

[](){[]()(){}}

Sample output 2:

Yes


In [24]:
a=input()
list1=[]
list11=[]
list2=[]
list21=[]
list3=[]
list31=[]
for i in a:
    if i=='(':
        list1.append(i)
        continue
    elif i==')':
        list11.append(i)
        continue
    elif i=='{':
        list2.append(i)
        continue
    elif i=='}':
        list21.append(i)
        continue
    elif i=='[':
        list3.append(i)
        continue
    elif i==']':
        list31.append(i)
if len(list1)==len(list11) and len(list2)==len(list21) and len(list3)==len(list31):
        print('yes')
else: print('no') 

    

){[[]]}())()
no


**Question-5**

You will be given a list of repeated elements. You have to find the maximum distance between two same elements. The answer will be zero if there are no repeated elements.

----------------------------------------------------------------------
Input:
A non-empty list of integers.

Output:
A single integer denoting the maximum distance between two same integers.

----------------------------------------------------------------------
Sample input:

[1, 2, 3, 2, 5, 1, 2, 4, 6, 2, 7, 8, 6]

Sample output:

8

Explanation:

Max distance for 1: 5

Max distance for 2: 8

Max distance for 3: 0

Max distance for 4: 0

Max distance for 5: 0

Max distance for 6: 4

Max distance for 7: 0

Max distance for 8: 0

In [33]:
l=eval(input())
setl=set(l)
list2=[]
print(setl)
for i in setl:
    list1=[]
    count=0
    for x in l:
        count=count+1
        if x==i:
            list1.append(count)
    list2.append(max(list1)-min(list1))
    
print(max(list2))


[1,2,3,4,4,4,5,5,6,6,3,4,5,7,8,1,1,1,2]
{1, 2, 3, 4, 5, 6, 7, 8}
17


**Question-6:**

You have an array of integers of length n spanning 0 to n with one missing. Write a function missing_number that returns the missing number in the array.

Sample Input:

[0,1,2,4,5] 

Sample Output:

missing_number(nums) -> 3

In [35]:
a=eval(input())
l=len(a)
for i in range(l+1):
    if a[i]!=i:
        print(i)
        break


[0,1,2,4,5]
3


**Question-7:**

Let’s say there are many vehicles on a long road. At each mile along the road, a checkpoint indicates the length traveled across the road.

You are given a list called vehicles which indicates the number of vehicles between each checkpoint. For example, the list [7,4,3] would mean that there are seven vehicles before the first checkpoint, four vehicles between the first and second checkpoints, and three vehicles between the second and third checkpoints.

Write a function range_vehicles that will give the number of vehicles between the start and end checkpoints.

Note: start may be 0

**Input:**

vehicles = [5,6,4,2,1]

start = 1

end = 3

**Output:**

10

In [37]:
def range_vehicles(a,start,end):
    
    new_list=a[start:end]
    result=sum(new_list)
    return result

b=eval(input())
c=int(input())
d=int(input())

range_vehicles(b,c,d)
    

[5,6,4,2,1]
1
3


10

**Question-8**

Given a dictionary with keys of letters and values of a list of letters, write a function closest_key to find the key with the input value closest to the beginning of the list.

**Input:**

dictionary = {
    'a' : ['b','c','e'],
    'm' : ['c','e'],
}

input = 'c'

**Ouput:**

m

In [8]:
dictionary=eval(input())
a=input()
list1=[]

for k,v in dictionary.items():
     for i in v:
            if i==a:
                list1.append(v.index(i))
                break
                
index1=min(list1)

for k,v in dictionary.items():
    if v[index1]==a:
        print(k)

{ 'a' : ['b','c','e'], 'm' : ['c','e'], 'z' : ['c','a','d']} 
c
m
z


**Question-9**

You are given a string that represents some floating-point number. Write a function, digit_accumulator, that returns the sum of every digit in the string.

**Input:**

s = "123.0045"

**Output:**

15

In [3]:
a=str(input())
list1=[*a]
list2=[int(i) for i in list1 if i!='.' and i!=',']
print(sum(list2))

123.0045
15


**Question-10**

Using the Map function, create a list 'cube', which consists of the cube of numbers in input_list.

Input:

[5,6,4,8,9] 

Output:

[125, 216, 64, 512, 729].

In [13]:
a=eval(input())
print(a)
b=list(map(lambda x:x**3, a))
print(b)

[5,6,4,8,9]
[5, 6, 4, 8, 9]
[125, 216, 64, 512, 729]


**Question-11**

Create a list ‘name’ consisting of the combination of the first name and the second name from list 1 and 2 respectively. 


Input:

[ ['Ankur', 'Avik', 'Kiran', 'Nitin'], ['Narang', 'Sarkar', 'R', 'Sareen']]

Output:

['Ankur Narang', 'Avik Sarkar', 'Kiran R', 'Nitin Sareen']

In [24]:
a=eval(input())
list1=[a[0][i] + ' '+ a[1][i] for i in range(len(a[0]))]
print(list1)
    

[ ['Ankur', 'Avik', 'Kiran', 'Nitin'], ['Narang', 'Sarkar', 'R', 'Sareen']]
['Ankur Narang', 'Avik Sarkar', 'Kiran R', 'Nitin Sareen']


**Question-12**

Add the element ‘Python’ to a tuple input_tuple = ('Monty Python', 'British', 1969). 

import ast
a=ast.literal_eval(input())
b=eval(input())
result=(*a,b)
result1=a+b
result2=sum(a,b)
print(result)
print(result1)
print(result2)

In [28]:
string_to_split = 'Hi.Can.we.get.rid.of.the.periods.here'
out = " ".join(string_to_split.split('.'))
print(out5)

Hi Can we get rid of the periods here
No Python documentation found for 'Hi Can we get rid of the periods here'.
Use help() to get the interactive help utility.
Use help(str) for help on the str class.



In [8]:
a='jhbvhhjb'
print(a.upper())

JHBVHHJB


In [2]:
list1=[1,2,3,4,5]
list1.insert(1, (2,3))


In [3]:
print(list1)

[1, (2, 3), 2, 3, 4, 5]


In [11]:
a=int(input())
list1=[]
for i in range(a):
    listb=((input().split(' ')))
    list1.append(listb)
listf=[]
for i in list1:
    if i[0]=='insert':
        listf.insert(int(i[1]), int(i[2]))
    elif i[0]=='print':
        print(listf, end="\n")
    elif i[0]=='remove':
        listf.remove(int(i[1]))
    elif i[0]=='append':
        listf.append(int(i[1]))
    elif i[0]=='sort':
        listf.sort()
    elif i[0]=='pop':
        listf.pop()
    elif i[0]=='reverse':
        listf.reverse()
        


12
insert 0 5
insert 1 10
insert 0 6
print
remove 6
append 9
append 1
sort
print
pop
reverse
print
[6, 5, 10]
[1, 5, 9, 10]
[9, 5, 1]


In [25]:
x=int(input())
a=input().split(' ')
b=[int(i) for i in a]
tup=tuple(b)
print(hash(tup))

2
1 2
-3550055125485641917


In [24]:
b=tuple(map(int, input().split(' ')))
print(hash(b))

1 2
-3550055125485641917


In [1]:
import numpy as np
a=tuple(map(int, input().split(' ')))
print(np.zeros(a, dtype='int'))
# print(b)
print(np.ones(a, dtype='int'))
# print(c)

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [10]:
a=list(map(int, input().split(' ')))
a.reverse()
b=np.array(a)
b

1 2 3 4 -8 -10


array([-10,  -8,   4,   3,   2,   1])

In [19]:
import numpy

def arrays(arr):
    a=list(map(float, arr))
    a.reverse()
    b=np.array(a)
    return b    
    
arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1.1 -1.2
[-1.2  1.1]


In [20]:
a=list(map(int, input().split(' ')))
b=np.array(a)
b.shape=(3,3)
print(b)


1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [35]:
sh=tuple(map(int, input().split(' ')))
a=[]
for i in range(sh[0]): 
    a.append(list(map(int, input().split(' '))))


arr=np.array(a)
arr.shape=sh
arr1=np.transpose(arr)
print(arr1)
arr2=arr.flatten()
print(arr2)


3 2
1 2
3 4
5 6
[[1 3 5]
 [2 4 6]]
[1 2 3 4 5 6]


In [51]:
import numpy as np
a=list(map(int , input().split(' ')))
count=0
b=[]
c=[]
for i in a:
    count=count+1
    if count==1:
        for x in range(i):
            b.extend(input().split(' ')) 
    elif count==2:
        for y in range(i):
            c.extend(input().split(' '))
    elif count==3:
        break
        
b=list(map(int,b))
c=list(map(int,c))
arr1=np.array(b)
arr2=np.array(c)
sh1=tuple(a[0:3:2])
sh2=tuple(a[1:3])
arr1.shape=sh1
arr2.shape=sh2

print(np.concatenate((arr1,arr2), axis=0))

2 2 2
1 2
3 4
5 6
7 8
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [14]:
import numpy as np
a=int(input())
b=[]
for i in range(a):
    b.extend(list(map(float,(input().strip().split(' ')))))

x=np.array(b, dtype='float').reshape((a,a))
print(round(np.linalg.det(x), 2))
    

2
1.1 1.1
1.1 1.1
0.0


In [16]:
import pandas as pd
df=pd.read_csv('https://raw.githubusercontent.com/ingledarshan/upGrad_Darshan/main/student_records.csv')
df

Name OverallGrade Obedient  ResearchScore  ProjectScore Recommend
0   Henry            A        Y             90            85       Yes
1    John            C        N             85            51       Yes
2   David            F        N             10            17        No
3  Holmes            B        Y             75            71        No
4  Marvin            E        N             20            30        No
5   Simon            A        Y             92            79       Yes
6  Robert            B        Y             60            59        No
7   Trent            C        Y             75            33        No

In [37]:
df['Name'].str[-3:-1]

0    nr
1    oh
2    vi
3    me
4    vi
5    mo
6    er
7    en
Name: Name, dtype: object

In [39]:
df.describe()

ResearchScore  ProjectScore
count       8.000000      8.000000
mean       63.375000     53.125000
std        31.640559     24.752705
min        10.000000     17.000000
25%        50.000000     32.250000
50%        75.000000     55.000000
75%        86.250000     73.000000
max        92.000000     85.000000